# Generated by Django 4.0.4 on 2022-06-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_art', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=40)),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('descripcion', models.CharField(max_length=40)),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vendedor', models.CharField(max_length=40)),
                ('cuit', models.IntegerField()),
                ('direccion', models.CharField(max_length=40)),
                ('emaeil', models.EmailField(max_length=254)),
                ('id_usuario', models.IntegerField()),
            ],
        ),
    ]
